### ISSUE TITLE
Extension can't find Autotrace on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by barkengmad** [fablabnbg/inkscape-centerline-trace#27] opened 2018-09-03 22:28 UTC
I have been using the Centerline Trace extension with great results. However, I have just upgraded from Ubuntu 16.04 to 18.04. On doing so, Inkscape (0.92.3) disappeared from my machine and I re-installed (via official PPA). Inkscape once again works as expected. I have re-installed the latest versions of both centerline trace and its dependency autotrace, but on trying to apply a trace on an image in inkscape, i get the following message...

"You need to install autotrace for this extension to work. Try https://github.com/jnweiger/autotrace/releases or google for autotrace version 0.40.0 or later. (Windows: see https://sourceforge.net/projects/autotrace/ )"

I have tried uninstalling/reinstalling both Centerline Trace and AutoRoute many times. I have also installed older version (Centerline 0.71 and Autotrace 0.31) but outputs a similar message. I have installed the latest versions of the extensions on another 16.04 Ubuntu machine, ending up with the same error.

**Comment by Moini** [comment] 2018-09-03 22:43
What do you get when you run 
`autotrace --version` 
on the command line?

**Comment by jnweiger** [comment] 2018-09-04 07:50
Duplicate of https://github.com/autotrace/autotrace/issues/12
Please try installing
https://github.com/jnweiger/autotrace/releases/download/travis-20180902.109/autotrace_0.40.0-20180903-ubuntu1804_all.deb

and also (probably less important)

https://github.com/fablabnbg/inkscape-centerline-trace/releases/download/v0.8b/inkscape-centerline-trace_0.8b-20180904_all.deb

**Comment by jnweiger** [comment] 2018-09-04 08:32
We need to verify how inkscape-centerline-trace on ubuntu-18.04 behaves if autotrace-0.40.0 compiled for Ubuntu 16.04 is installed. It should be able give a hint.

**Comment by barkengmad** [comment] 2018-09-04 08:55
It did output "autotrace: error while loading shared libraries: libMagickCore.so.5: cannot open shared object file: No such file or directory"
But now have installed first link autotrace_0.40.0-20180903-ubuntu1804_all.deb
Now outputs "AutoTrace version 0.40.0." **and now works perfectly!**
Thanks so much for the update. This extension is critical for a project with a pending deadline. You have really saved my bacon!
Cheers, Morgan.

**Comment by barkengmad** [comment] 2018-09-04 08:56
I will have access to my other 16.04 LTS machine later tonight, if you want me to test on that also.

**Comment by jnweiger** [comment] 2018-09-04 20:15
On my ubuntu-18.04 machine I have /usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.3 installed and the error message is "autotrace: error while loading shared libraries: libMagickCore-6.Q16.so.2: cannot open shared object file: No such file or directory"

In the next release of inkscape-centerline-trace the error popup will say

```
autotrace: error while loading shared libraries: libMagickCore-6.Q16.so.2:
cannot open shared object file: No such file or directory

NOTE: This build of autotrace is incompatible with your system, try a
different build.

You need to install autotrace for this extension to work. Try
https://github.com/jnweiger/autotrace/releases or search for autotrace version 0.40.0 or later.
```
Hope that gives the right hints. Just claiming that autotrace was not installed after it successfully installed was not the best message :-)

Closing here.

@barkengmad if you find that the other DEB package (not explicitly marked as ubuntu1804) fails on your 16.04 LTS, please reopen.

**Closed by jnweiger** 2018-09-04 20:15 UTC

**Comment by davidhealey** [comment] 2020-02-19 02:38
I'm getting this same issue. I'm on Linux Mint 19
