### ISSUE TITLE
Erroe help

### ISSUE THREAD

**Issue by mole20** [fablabnbg/inkscape-centerline-trace#14] opened 2017-06-14 20:10 UTC
Already installed Pillow for my installed version of Python (3.5)  still getting this error:

Error: Cannot import PIL. Try
  apt-get install python-pil

Please help.
Thanks

**Comment by jnweiger** [comment] 2017-07-28 15:06
Whicj opeeating system is this?

**Comment by Moini** [comment] 2017-08-01 00:33
Additional info: 
Inkscape doesn't use python 3, but 2.7 (unless you edit the preferences file manually, but then the other extensions will probably break).

On Windows, Inkscape brings its own directory with python modules and python 2.7.

**Comment by jnweiger** [comment] 2018-09-04 12:30
probably a duplicate of #16 - see there for the fix. closing here.

**Closed by jnweiger** 2018-09-04 12:30 UTC
